import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import Listing from '../components/Listing.js'
import Button from '../components/Button'

export default function Home(props) {
  const listings = props.data;
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Nexus Point Tech Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h1>CarDealer <sup>UK</sup></h1>
        <nav className={styles.main_navbar}>
        </nav>
      </header>
      <main>
        <aside className={styles.finance_banner}>
          <h1>Finance Banner</h1>
        </aside>
        <div className={styles.main_content}>
          <section className={styles.search_sidebar}>
            <h1>Filters</h1>
            <nav>
              <Button label={"Make"}/>
            </nav>
          </section>
          <section className={styles.listing_feed}>
            <h1>Listing Feed</h1>
            <div className={styles.listing_grid}>
              {
                listings.map((listing, index)=>
                  <Listing key={listing.advertisable_id} data = {listing} order={index}/>
                )
              }
            </div>
          </section>
        </div>
      </main>
      <footer className={styles.footer}>
        <h1>Footer</h1>
      </footer>
      
    </div>
  )
}

import fsPromises from 'fs/promises';
import path from 'path'
export async function getStaticProps() {
  const filePath = path.join(process.cwd(), 'mock-vehicle-search-response.json');
  const jsonData = await fsPromises.readFile(filePath);
  const objectData = JSON.parse(jsonData);

  return {
    props: objectData
  }
}
