import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import Listing from '../components/Listing.js'

export default function Home(props) {
  const listings = props.data;
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Nexus Point Tech Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.navbar}>
        <h1>Header</h1>
      </nav>
      <div className={styles.finance_banner}>
        <h2>finance banner</h2>
      </div>
      <div className={styles.search_sidebar}>
        <h3>Search Sidebar</h3>
      </div>
      <main className={styles.listing_feed}>
        <h3>Listing Feed</h3>
        <div className={styles.listing_grid}>
          {
            listings.map((listing, index)=>
              <Listing key={listing.advertisable_id} data = {listing} order={index}/>
            )
          }
        </div>
      </main>
      <footer className={styles.footer}>
        <h4>footer</h4>
      </footer>
      
    </div>
  )
}

import fsPromises from 'fs/promises';
import path from 'path'
export async function getStaticProps() {
  const filePath = path.join(process.cwd(), 'mock-vehicle-search-response.json');
  const jsonData = await fsPromises.readFile(filePath);
  const objectData = JSON.parse(jsonData);

  return {
    props: objectData
  }
}
